### PR TITLE
Make worker maximum sleep time configurable

### PR DESCRIPTION
**Pull request by achauve**

### CODE REVIEW

**Comment by achauve** [comment]
@sylvinus Is this PR ok with you or would you like some improvements?

**Comment by sylvinus** [comment]
Looks good, sorry for the lag!

Maybe max_latency would be a better name for the config option?

**Comment by achauve** [comment]
Yes I hesitated because latency could also come from other parts but still that makes more sense.
Done!

**Comment by sylvinus** [comment]
Thanks!

**Pull request merged**
