### PR TITLE
Order table

### PR DESCRIPTION
**Pull request by mvquezm**

### CODE REVIEW

**Comment by mvquezm** [comment]
A naive mistake selecting the forked MRQ repository

**Comment by sylvinus** [comment]
@mvquezm hi! didn't you want that merged into mrq ?

**Comment by mvquezm** [comment]
Hi, it was a mistake, changes are not ready yet, when will be ready i will create a pull request again, best regards M

**Comment by sylvinus** [comment]
Okay well let me know if you want some feedback anyway! For instance I think it would be way better to use an existing javascript widget (for instance http://www.daterangepicker.com/) than to reimplement it :)

**Pull request closed without merging**
